/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp org.thebesttv.PonyOCR.xml -a ponyocr_adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2019 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ponyocr_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QTimer>

/*
 * Implementation of adaptor class PonyOCRAdaptor
 */

PonyOCRAdaptor::PonyOCRAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

PonyOCRAdaptor::~PonyOCRAdaptor()
{
    // destructor
}

void PonyOCRAdaptor::requestOCR()
{
    // handle method call org.thebesttv.PonyOCR.requestOCR
    QTimer::singleShot(0, [this](){
        QMetaObject::invokeMethod(parent(), "requestOCR");
    });
}

